server:
  port: 8080
  servlet:
    contextPath: "/sc-core"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sport-connection?serverTimezone=UTC"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    initialization-mode: "always"
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
