server:
  port: 8080
  servlet:
    contextPath: "/sc-core"

spring:
  datasource:
    url: "jdbc:mysql://banco:3306/sport-connection?serverTimezone=UTC"
    #username: ${MYSQL_USERNAME}
    username: root
    #password: ${MYSQL_PASSWORD}
    password: admin
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    initialization-mode: "always"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    show_sql: true
    format_sql: true
    hibernate:
      #ddl-auto: update
      ddl-auto: create

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

jwt:
  #secret: ${JWT_SECRET}
  secret: s3cr373jwts3cr373jwts3cr373jwts3cr373jwts3cr373jwts3cr373jwt
  expirationInSeconds: 10800